/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * 
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.10.3/userguide/multi_project_builds.html
 */

rootProject.name = "LittleBoy"

pluginManagement {
    resolutionStrategy {
        eachPlugin {
            when {
                requested.id.id.startsWith("com.android.") ->
                    useModule("com.android.tools.build:gradle:3.5.3")
                requested.id.id.startsWith("org.jetbrains.kotlin.") ->
                    useVersion(embeddedKotlinVersion)
                requested.id.id == "com.jfrog.bintray" ->
                    useVersion("1.8.4")
            }
        }
    }
    repositories {
        @Suppress("UnstableApiUsage")
        gradlePluginPortal()
        google()
        jcenter()
    }
}


include(":urho3d-lib", ":launcher-app")

project(":urho3d-lib").projectDir = File(settingsDir, "../../Urho3D/android/urho3d-lib")
